# This task adds Docker's official GPG key to ensure that the software package is genuine.
- name: Add Docker's official GPG key
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

# This task adds the Docker repository to the system's repository list. It specifies the repo based on the host's Ubuntu version.
- name: Add Docker repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present
    update_cache: yes

# This task installs the Docker Engine from the added repository.
- name: Install Docker Engine
  become: true
  ansible.builtin.apt:
    name: docker-ce
    state: present
  notify: restart docker  # Triggers a handler to restart Docker if necessary.

# This task installs Docker Compose using pip. Docker Compose is a tool for defining and running multi-container Docker applications.
- name: Install Docker Compose
  become: true
  ansible.builtin.pip:
    name: docker-compose
    state: present
